version: "3.9"
networks:
  myAppNetwork:
    driver: bridge

services:
  postgresServerDb:
    container_name: container-postgres
    image: postgres:16.1
    ports:
      - "5022:5432"
    environment:
      - POSTGRES_USER=minipig
      - POSTGRES_PASSWORD=p%rSDj4I77mds07djc**dmUnt00dOidd3dZ_#WTi4B9Zo
      - POSTGRES_DB=pd211
    networks:
      - myAppNetwork
    volumes:
       - d:/volumes/pd211/postgresql:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  app:
    container_name: test_container
    image: mirada032/pd211-java
    ports:
      - "5062:8083"
    networks:
      - myAppNetwork
    depends_on:
      - postgresServerDb
    volumes:
       - d:/volumes/pd211/images:/app/images
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  react-app:
    container_name: react-container
    image: mirada032/pd211-react
    ports:
      - "5723:80"
    networks:
      - myAppNetwork
    depends_on:
      - app
    volumes:
      - d:/volumes/pd211/images:/react-app/images
    environment:
      - NODE_ENV=development
